'use client';

import React, { useState, useEffect } from 'react';
import { cn } from '@/lib/utils';
import {
  Book,
  Search,
  FileCode,
  Folder,
  Tag,
  Clock,
  ExternalLink,
  Loader2,
  Sparkles,
} from 'lucide-react';

interface WikiPage {
  id: string;
  title: string;
  slug: string;
  content: string;
  sourceFiles: string[];
  category: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
  autoGenerated: boolean;
}

interface WikiPanelProps {
  sessionId: string;
  className?: string;
  onLoadPages?: () => Promise<WikiPage[]>;
  onGenerateWiki?: () => Promise<WikiPage[]>;
  onViewFile?: (filePath: string, line?: number) => void;
}

export function WikiPanel({
  sessionId,
  className,
  onLoadPages,
  onGenerateWiki,
  onViewFile,
}: WikiPanelProps) {
  const [pages, setPages] = useState<WikiPage[]>([]);
  const [selectedPage, setSelectedPage] = useState<WikiPage | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [filterCategory, setFilterCategory] = useState<string | null>(null);

  useEffect(() => {
    loadPages();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId]);

  const loadPages = async () => {
    setLoading(true);
    try {
      const loaded = await onLoadPages?.();
      if (loaded) {
        setPages(loaded);
        if (loaded.length > 0 && !selectedPage) {
          setSelectedPage(loaded[0] ?? null);
        }
      }
    } catch (err) {
      console.error('Failed to load wiki pages:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const generated = await onGenerateWiki?.();
      if (generated) {
        setPages(generated);
        if (generated.length > 0) {
          setSelectedPage(generated[0] ?? null);
        }
      }
    } catch (err) {
      console.error('Failed to generate wiki:', err);
    } finally {
      setGenerating(false);
    }
  };

  // Get unique categories
  const categories = [...new Set(pages.map((p) => p.category))];

  // Filter pages
  const filteredPages = pages.filter((page) => {
    const matchesSearch =
      !searchQuery ||
      page.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      page.tags.some((t) => t.toLowerCase().includes(searchQuery.toLowerCase()));
    const matchesCategory = !filterCategory || page.category === filterCategory;
    return matchesSearch && matchesCategory;
  });

  // Group by category
  const pagesByCategory = filteredPages.reduce(
    (acc, page) => {
      if (!acc[page.category]) {
        acc[page.category] = [];
      }
      acc[page.category]!.push(page);
      return acc;
    },
    {} as Record<string, WikiPage[]>
  );

  return (
    <div className={cn('flex h-full', className)}>
      {/* Sidebar */}
      <div className="w-64 flex-shrink-0 border-r border-border-subtle flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border-subtle">
          <div className="flex items-center gap-2">
            <Book className="w-5 h-5 text-accent-primary" />
            <h3 className="font-semibold">Wiki</h3>
          </div>
          <button
            onClick={handleGenerate}
            disabled={generating}
            className="p-1.5 rounded hover:bg-surface-hover text-text-muted"
            title="Regenerate documentation"
          >
            {generating ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
          </button>
        </div>

        {/* Search */}
        <div className="px-3 py-2 border-b border-border-subtle">
          <div className="relative">
            <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search docs..."
              className="w-full pl-8 pr-3 py-1.5 text-sm rounded border border-border-subtle bg-surface-primary focus:outline-none focus:border-accent-primary"
            />
          </div>
        </div>

        {/* Category Filter */}
        {categories.length > 1 && (
          <div className="flex gap-1 px-3 py-2 border-b border-border-subtle overflow-x-auto">
            <button
              onClick={() => setFilterCategory(null)}
              className={cn(
                'px-2 py-1 text-xs rounded whitespace-nowrap',
                !filterCategory
                  ? 'bg-accent-primary/20 text-accent-primary'
                  : 'bg-surface-secondary text-text-muted hover:text-text-primary'
              )}
            >
              All
            </button>
            {categories.map((cat) => (
              <button
                key={cat}
                onClick={() => setFilterCategory(cat)}
                className={cn(
                  'px-2 py-1 text-xs rounded capitalize whitespace-nowrap',
                  filterCategory === cat
                    ? 'bg-accent-primary/20 text-accent-primary'
                    : 'bg-surface-secondary text-text-muted hover:text-text-primary'
                )}
              >
                {cat}
              </button>
            ))}
          </div>
        )}

        {/* Page List */}
        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="flex items-center justify-center py-8">
              <Loader2 className="w-5 h-5 animate-spin text-text-muted" />
            </div>
          ) : pages.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-8 px-4 text-center">
              <Book className="w-8 h-8 mb-2 opacity-50 text-text-muted" />
              <p className="text-sm text-text-muted">No documentation yet</p>
              <button
                onClick={handleGenerate}
                disabled={generating}
                className="mt-3 flex items-center gap-1.5 px-3 py-1.5 text-sm rounded bg-accent-primary text-white hover:bg-accent-primary/90"
              >
                <Sparkles className="w-4 h-4" />
                Generate Wiki
              </button>
            </div>
          ) : (
            <div className="py-2">
              {Object.entries(pagesByCategory).map(([category, categoryPages]) => (
                <div key={category}>
                  <div className="px-4 py-1 text-xs font-medium text-text-muted uppercase tracking-wider">
                    {category}
                  </div>
                  {categoryPages.map((page) => (
                    <button
                      key={page.id}
                      onClick={() => setSelectedPage(page)}
                      className={cn(
                        'w-full px-4 py-2 text-left hover:bg-surface-hover transition-colors flex items-center gap-2',
                        selectedPage?.id === page.id && 'bg-accent-primary/10'
                      )}
                    >
                      <FileCode className="w-4 h-4 text-text-muted flex-shrink-0" />
                      <span className="text-sm truncate">{page.title}</span>
                    </button>
                  ))}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {selectedPage ? (
          <>
            {/* Page Header */}
            <div className="px-6 py-4 border-b border-border-subtle">
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-xl font-semibold">{selectedPage.title}</h1>
                  <div className="flex items-center gap-4 mt-2 text-xs text-text-muted">
                    <span className="flex items-center gap-1">
                      <Folder className="w-3 h-3" />
                      {selectedPage.category}
                    </span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      {new Date(selectedPage.updatedAt).toLocaleDateString()}
                    </span>
                    {selectedPage.autoGenerated && (
                      <span className="flex items-center gap-1 text-purple-500">
                        <Sparkles className="w-3 h-3" />
                        Auto-generated
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Tags */}
              {selectedPage.tags.length > 0 && (
                <div className="flex items-center gap-2 mt-3">
                  <Tag className="w-4 h-4 text-text-muted" />
                  {selectedPage.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-2 py-0.5 text-xs rounded bg-surface-secondary text-text-muted"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* Page Content */}
            <div className="flex-1 overflow-y-auto px-6 py-4">
              <div
                className="prose prose-sm prose-invert max-w-none"
                dangerouslySetInnerHTML={{
                  __html: renderMarkdown(selectedPage.content),
                }}
              />
            </div>

            {/* Source Files */}
            {selectedPage.sourceFiles.length > 0 && (
              <div className="px-6 py-3 border-t border-border-subtle bg-surface-secondary/50">
                <p className="text-xs font-medium text-text-muted mb-2">Source Files</p>
                <div className="flex flex-wrap gap-2">
                  {selectedPage.sourceFiles.map((file) => (
                    <button
                      key={file}
                      onClick={() => onViewFile?.(file)}
                      className="flex items-center gap-1 px-2 py-1 text-xs rounded bg-surface-primary border border-border-subtle hover:border-accent-primary transition-colors"
                    >
                      <FileCode className="w-3 h-3" />
                      {file.split('/').pop()}
                      <ExternalLink className="w-3 h-3" />
                    </button>
                  ))}
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-text-muted">
            <div className="text-center">
              <Book className="w-12 h-12 mx-auto mb-3 opacity-50" />
              <p>Select a page to view</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// Simple markdown renderer (replace with proper library in production)
function renderMarkdown(content: string): string {
  return content
    .replace(/^### (.+)$/gm, '<h3 class="text-lg font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-xl font-semibold mt-6 mb-3">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold mt-6 mb-4">$1</h1>')
    .replace(
      /`([^`]+)`/g,
      '<code class="px-1.5 py-0.5 rounded bg-surface-secondary text-accent-primary font-mono text-sm">$1</code>'
    )
    .replace(
      /```(\w*)\n([\s\S]*?)```/g,
      '<pre class="p-3 rounded bg-surface-secondary overflow-x-auto my-3"><code class="text-sm font-mono">$2</code></pre>'
    )
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li class="ml-4">$1</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul class="list-disc my-2">$&</ul>')
    .replace(/^\| (.+) \|$/gm, '<tr><td class="border border-border-subtle px-3 py-1">$1</td></tr>')
    .replace(/\n\n/g, '</p><p class="my-2">')
    .replace(/^(.+)$/gm, '<p class="my-2">$1</p>');
}

export default WikiPanel;
