import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Podex Terms of Service. Read the terms and conditions for using the Podex platform.',
  alternates: {
    canonical: '/terms',
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-void py-24 lg:py-32">
      <div className="mx-auto max-w-3xl px-4 lg:px-8">
        <h1 className="text-4xl font-bold text-text-primary mb-4">Terms of Service</h1>
        <p className="text-text-muted mb-12">Last updated: January 1, 2025</p>

        <div className="prose prose-invert max-w-none">
          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">1. Acceptance of Terms</h2>
            <p className="text-text-secondary">
              By accessing or using Podex (&quot;Service&quot;), you agree to be bound by these
              Terms of Service (&quot;Terms&quot;). If you disagree with any part of the terms, you
              may not access the Service.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">2. Description of Service</h2>
            <p className="text-text-secondary">
              Podex is a web-based development platform that provides AI-powered coding assistance,
              cloud computing resources, and collaboration tools. We reserve the right to modify,
              suspend, or discontinue any aspect of the Service at any time.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">3. User Accounts</h2>
            <ul className="list-disc pl-6 text-text-secondary space-y-2">
              <li>You must be at least 16 years old to use the Service</li>
              <li>You are responsible for maintaining the security of your account</li>
              <li>You must provide accurate and complete registration information</li>
              <li>You are responsible for all activities under your account</li>
              <li>Notify us immediately of any unauthorized use</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">4. Acceptable Use</h2>
            <p className="text-text-secondary mb-4">You agree not to:</p>
            <ul className="list-disc pl-6 text-text-secondary space-y-2">
              <li>Use the Service for any illegal purpose</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Transmit malware or harmful code</li>
              <li>Attempt to gain unauthorized access</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Use the Service to harass or harm others</li>
              <li>Scrape or collect data without permission</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">5. Your Content</h2>
            <p className="text-text-secondary mb-4">
              You retain ownership of content you create using the Service. By using the Service,
              you grant us a license to:
            </p>
            <ul className="list-disc pl-6 text-text-secondary space-y-2">
              <li>Store and process your content to provide the Service</li>
              <li>Create backups for disaster recovery</li>
              <li>Use anonymized data to improve our services</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">6. AI-Generated Content</h2>
            <p className="text-text-secondary">
              Code and content generated by our AI agents is provided &quot;as is.&quot; You are
              responsible for reviewing, testing, and ensuring the suitability of AI-generated
              content before use in production environments.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">7. Payment Terms</h2>
            <ul className="list-disc pl-6 text-text-secondary space-y-2">
              <li>Paid plans are billed in advance on a monthly or annual basis</li>
              <li>All fees are non-refundable unless otherwise stated</li>
              <li>We may change pricing with 30 days notice</li>
              <li>You are responsible for applicable taxes</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">8. Intellectual Property</h2>
            <p className="text-text-secondary">
              The Service and its original content, features, and functionality are owned by Podex
              and are protected by international copyright, trademark, and other intellectual
              property laws.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">
              9. Disclaimer of Warranties
            </h2>
            <p className="text-text-secondary">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM
              ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A
              PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">
              10. Limitation of Liability
            </h2>
            <p className="text-text-secondary">
              IN NO EVENT SHALL PODEX BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">11. Termination</h2>
            <p className="text-text-secondary">
              We may terminate or suspend your account at any time, with or without cause, with or
              without notice. Upon termination, your right to use the Service will immediately
              cease.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-bold text-text-primary mb-4">12. Governing Law</h2>
            <p className="text-text-secondary">
              These Terms shall be governed by the laws of the State of California, without regard
              to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-text-primary mb-4">13. Contact Us</h2>
            <p className="text-text-secondary">
              If you have questions about these Terms, please contact us at{' '}
              <a href="mailto:legal@podex.dev" className="text-accent-primary hover:underline">
                legal@podex.dev
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
