/**
 * Default VS Code-compatible keyboard shortcuts
 */

import type { Keybinding } from './KeybindingManager';

export const defaultKeybindings: Keybinding[] = [
  // ==================== Navigation ====================
  {
    id: 'quickOpen',
    key: 'mod+p',
    command: 'quickOpen.toggle',
    description: 'Quick open file',
    category: 'Navigation',
  },
  {
    id: 'commandPalette',
    key: 'mod+shift+p',
    command: 'commandPalette.toggle',
    description: 'Open command palette',
    category: 'Navigation',
  },
  {
    id: 'goToLine',
    key: 'mod+g',
    command: 'editor.goToLine',
    when: 'editorFocus',
    description: 'Go to line',
    category: 'Navigation',
  },
  {
    id: 'goToSymbol',
    key: 'mod+shift+o',
    command: 'editor.goToSymbol',
    when: 'editorFocus',
    description: 'Go to symbol in file',
    category: 'Navigation',
  },
  {
    id: 'goToDefinition',
    key: 'f12',
    command: 'editor.goToDefinition',
    when: 'editorFocus',
    description: 'Go to definition',
    category: 'Navigation',
  },
  {
    id: 'peekDefinition',
    key: 'alt+f12',
    command: 'editor.peekDefinition',
    when: 'editorFocus',
    description: 'Peek definition',
    category: 'Navigation',
  },
  {
    id: 'findReferences',
    key: 'shift+f12',
    command: 'editor.findReferences',
    when: 'editorFocus',
    description: 'Find all references',
    category: 'Navigation',
  },

  // ==================== View ====================
  {
    id: 'toggleSidebar',
    key: 'mod+b',
    command: 'sidebar.toggle',
    description: 'Toggle sidebar',
    category: 'View',
  },
  {
    id: 'toggleTerminal',
    key: 'mod+backtick',
    command: 'terminal.toggle',
    description: 'Toggle terminal',
    category: 'View',
  },
  {
    id: 'togglePanel',
    key: 'mod+j',
    command: 'panel.toggle',
    description: 'Toggle panel',
    category: 'View',
  },
  {
    id: 'focusFileExplorer',
    key: 'mod+shift+e',
    command: 'fileExplorer.focus',
    description: 'Focus file explorer',
    category: 'View',
  },
  {
    id: 'focusGit',
    key: 'mod+shift+g',
    command: 'git.focus',
    description: 'Focus source control',
    category: 'View',
  },
  {
    id: 'zoomIn',
    key: 'mod+=',
    command: 'view.zoomIn',
    description: 'Zoom in',
    category: 'View',
  },
  {
    id: 'zoomOut',
    key: 'mod+-',
    command: 'view.zoomOut',
    description: 'Zoom out',
    category: 'View',
  },
  {
    id: 'resetZoom',
    key: 'mod+0',
    command: 'view.resetZoom',
    description: 'Reset zoom',
    category: 'View',
  },

  // ==================== Editor ====================
  {
    id: 'splitEditor',
    key: 'mod+\\',
    command: 'editor.split',
    when: 'editorFocus',
    description: 'Split editor',
    category: 'Editor',
  },
  {
    id: 'closeTab',
    key: 'mod+w',
    command: 'editor.closeTab',
    when: 'editorFocus',
    description: 'Close tab',
    category: 'Editor',
  },
  {
    id: 'reopenClosedTab',
    key: 'mod+shift+t',
    command: 'editor.reopenClosedTab',
    description: 'Reopen closed tab',
    category: 'Editor',
  },
  {
    id: 'nextTab',
    key: 'mod+tab',
    command: 'editor.nextTab',
    description: 'Next tab',
    category: 'Editor',
  },
  {
    id: 'prevTab',
    key: 'mod+shift+tab',
    command: 'editor.prevTab',
    description: 'Previous tab',
    category: 'Editor',
  },
  {
    id: 'tab1',
    key: 'mod+1',
    command: 'editor.focusTab1',
    description: 'Go to tab 1',
    category: 'Editor',
  },
  {
    id: 'tab2',
    key: 'mod+2',
    command: 'editor.focusTab2',
    description: 'Go to tab 2',
    category: 'Editor',
  },
  {
    id: 'tab3',
    key: 'mod+3',
    command: 'editor.focusTab3',
    description: 'Go to tab 3',
    category: 'Editor',
  },
  {
    id: 'tab4',
    key: 'mod+4',
    command: 'editor.focusTab4',
    description: 'Go to tab 4',
    category: 'Editor',
  },
  {
    id: 'tab5',
    key: 'mod+5',
    command: 'editor.focusTab5',
    description: 'Go to tab 5',
    category: 'Editor',
  },

  // ==================== Find & Replace ====================
  {
    id: 'find',
    key: 'mod+f',
    command: 'editor.find',
    when: 'editorFocus',
    description: 'Find',
    category: 'Find',
  },
  {
    id: 'replace',
    key: 'mod+h',
    command: 'editor.replace',
    when: 'editorFocus',
    description: 'Replace',
    category: 'Find',
  },
  {
    id: 'findInFiles',
    key: 'mod+shift+f',
    command: 'search.findInFiles',
    description: 'Find in files',
    category: 'Find',
  },
  {
    id: 'replaceInFiles',
    key: 'mod+shift+h',
    command: 'search.replaceInFiles',
    description: 'Replace in files',
    category: 'Find',
  },
  {
    id: 'findNext',
    key: 'f3',
    command: 'editor.findNext',
    when: 'editorFocus',
    description: 'Find next',
    category: 'Find',
  },
  {
    id: 'findPrev',
    key: 'shift+f3',
    command: 'editor.findPrev',
    when: 'editorFocus',
    description: 'Find previous',
    category: 'Find',
  },
  {
    id: 'addSelectionToNextMatch',
    key: 'mod+d',
    command: 'editor.addSelectionToNextMatch',
    when: 'editorFocus',
    description: 'Add selection to next match',
    category: 'Find',
  },
  {
    id: 'selectAllOccurrences',
    key: 'mod+shift+l',
    command: 'editor.selectAllOccurrences',
    when: 'editorFocus',
    description: 'Select all occurrences',
    category: 'Find',
  },

  // ==================== Editing ====================
  {
    id: 'save',
    key: 'mod+s',
    command: 'editor.save',
    when: 'editorFocus',
    description: 'Save file',
    category: 'Edit',
  },
  {
    id: 'saveAll',
    key: 'mod+alt+s',
    command: 'editor.saveAll',
    description: 'Save all files',
    category: 'Edit',
  },
  {
    id: 'undo',
    key: 'mod+z',
    command: 'editor.undo',
    when: 'editorFocus',
    description: 'Undo',
    category: 'Edit',
  },
  {
    id: 'redo',
    key: 'mod+shift+z',
    command: 'editor.redo',
    when: 'editorFocus',
    description: 'Redo',
    category: 'Edit',
  },
  {
    id: 'redoAlt',
    key: 'mod+y',
    command: 'editor.redo',
    when: 'editorFocus',
    description: 'Redo',
    category: 'Edit',
  },
  {
    id: 'cut',
    key: 'mod+x',
    command: 'editor.cut',
    when: 'editorFocus',
    description: 'Cut',
    category: 'Edit',
  },
  {
    id: 'copy',
    key: 'mod+c',
    command: 'editor.copy',
    when: 'editorFocus',
    description: 'Copy',
    category: 'Edit',
  },
  {
    id: 'paste',
    key: 'mod+v',
    command: 'editor.paste',
    when: 'editorFocus',
    description: 'Paste',
    category: 'Edit',
  },
  {
    id: 'toggleComment',
    key: 'mod+/',
    command: 'editor.toggleComment',
    when: 'editorFocus',
    description: 'Toggle line comment',
    category: 'Edit',
  },
  {
    id: 'toggleBlockComment',
    key: 'mod+shift+/',
    command: 'editor.toggleBlockComment',
    when: 'editorFocus',
    description: 'Toggle block comment',
    category: 'Edit',
  },
  {
    id: 'deleteLine',
    key: 'mod+shift+k',
    command: 'editor.deleteLine',
    when: 'editorFocus',
    description: 'Delete line',
    category: 'Edit',
  },
  {
    id: 'moveLineUp',
    key: 'alt+up',
    command: 'editor.moveLineUp',
    when: 'editorFocus',
    description: 'Move line up',
    category: 'Edit',
  },
  {
    id: 'moveLineDown',
    key: 'alt+down',
    command: 'editor.moveLineDown',
    when: 'editorFocus',
    description: 'Move line down',
    category: 'Edit',
  },
  {
    id: 'copyLineUp',
    key: 'alt+shift+up',
    command: 'editor.copyLineUp',
    when: 'editorFocus',
    description: 'Copy line up',
    category: 'Edit',
  },
  {
    id: 'copyLineDown',
    key: 'alt+shift+down',
    command: 'editor.copyLineDown',
    when: 'editorFocus',
    description: 'Copy line down',
    category: 'Edit',
  },
  {
    id: 'insertLineBelow',
    key: 'mod+enter',
    command: 'editor.insertLineBelow',
    when: 'editorFocus',
    description: 'Insert line below',
    category: 'Edit',
  },
  {
    id: 'insertLineAbove',
    key: 'mod+shift+enter',
    command: 'editor.insertLineAbove',
    when: 'editorFocus',
    description: 'Insert line above',
    category: 'Edit',
  },
  {
    id: 'indentLine',
    key: 'mod+]',
    command: 'editor.indentLine',
    when: 'editorFocus',
    description: 'Indent line',
    category: 'Edit',
  },
  {
    id: 'outdentLine',
    key: 'mod+[',
    command: 'editor.outdentLine',
    when: 'editorFocus',
    description: 'Outdent line',
    category: 'Edit',
  },
  {
    id: 'formatDocument',
    key: 'mod+shift+i',
    command: 'editor.formatDocument',
    when: 'editorFocus',
    description: 'Format document',
    category: 'Edit',
  },
  {
    id: 'rename',
    key: 'f2',
    command: 'editor.rename',
    when: 'editorFocus',
    description: 'Rename symbol',
    category: 'Edit',
  },
  {
    id: 'quickFix',
    key: 'mod+.',
    command: 'editor.quickFix',
    when: 'editorFocus',
    description: 'Quick fix',
    category: 'Edit',
  },

  // ==================== Selection ====================
  {
    id: 'selectAll',
    key: 'mod+a',
    command: 'editor.selectAll',
    when: 'editorFocus',
    description: 'Select all',
    category: 'Selection',
  },
  {
    id: 'expandSelection',
    key: 'mod+shift+right',
    command: 'editor.expandSelection',
    when: 'editorFocus',
    description: 'Expand selection',
    category: 'Selection',
  },
  {
    id: 'shrinkSelection',
    key: 'mod+shift+left',
    command: 'editor.shrinkSelection',
    when: 'editorFocus',
    description: 'Shrink selection',
    category: 'Selection',
  },
  {
    id: 'addCursorAbove',
    key: 'mod+alt+up',
    command: 'editor.addCursorAbove',
    when: 'editorFocus',
    description: 'Add cursor above',
    category: 'Selection',
  },
  {
    id: 'addCursorBelow',
    key: 'mod+alt+down',
    command: 'editor.addCursorBelow',
    when: 'editorFocus',
    description: 'Add cursor below',
    category: 'Selection',
  },

  // ==================== Folding ====================
  {
    id: 'fold',
    key: 'mod+shift+[',
    command: 'editor.fold',
    when: 'editorFocus',
    description: 'Fold region',
    category: 'Folding',
  },
  {
    id: 'unfold',
    key: 'mod+shift+]',
    command: 'editor.unfold',
    when: 'editorFocus',
    description: 'Unfold region',
    category: 'Folding',
  },
  {
    id: 'foldAll',
    key: 'mod+k mod+0',
    command: 'editor.foldAll',
    when: 'editorFocus',
    description: 'Fold all regions',
    category: 'Folding',
  },
  {
    id: 'unfoldAll',
    key: 'mod+k mod+j',
    command: 'editor.unfoldAll',
    when: 'editorFocus',
    description: 'Unfold all regions',
    category: 'Folding',
  },

  // ==================== Agent / AI ====================
  {
    id: 'inlineChat',
    key: 'mod+i',
    command: 'agent.inlineChat',
    when: 'editorFocus',
    description: 'Open inline chat',
    category: 'AI',
  },
  {
    id: 'explainCode',
    key: 'mod+k mod+e',
    command: 'agent.explainCode',
    when: 'editorFocus',
    description: 'Explain selected code',
    category: 'AI',
  },
  {
    id: 'fixCode',
    key: 'mod+k mod+f',
    command: 'agent.fixCode',
    when: 'editorFocus',
    description: 'Fix selected code',
    category: 'AI',
  },
  {
    id: 'refactorCode',
    key: 'mod+k mod+r',
    command: 'agent.refactorCode',
    when: 'editorFocus',
    description: 'Refactor selected code',
    category: 'AI',
  },
  {
    id: 'generateTests',
    key: 'mod+k mod+t',
    command: 'agent.generateTests',
    when: 'editorFocus',
    description: 'Generate tests for selection',
    category: 'AI',
  },
  {
    id: 'addDocumentation',
    key: 'mod+k mod+d',
    command: 'agent.addDocumentation',
    when: 'editorFocus',
    description: 'Add documentation',
    category: 'AI',
  },
  {
    id: 'acceptSuggestion',
    key: 'tab',
    command: 'agent.acceptSuggestion',
    when: 'editorFocus && suggestionVisible',
    description: 'Accept AI suggestion',
    category: 'AI',
  },
  {
    id: 'dismissSuggestion',
    key: 'esc',
    command: 'agent.dismissSuggestion',
    when: 'editorFocus && suggestionVisible',
    description: 'Dismiss AI suggestion',
    category: 'AI',
  },
  {
    id: 'nextSuggestion',
    key: 'alt+]',
    command: 'agent.nextSuggestion',
    when: 'editorFocus && suggestionVisible',
    description: 'Next AI suggestion',
    category: 'AI',
  },
  {
    id: 'prevSuggestion',
    key: 'alt+[',
    command: 'agent.prevSuggestion',
    when: 'editorFocus && suggestionVisible',
    description: 'Previous AI suggestion',
    category: 'AI',
  },

  // ==================== Git ====================
  {
    id: 'gitCommit',
    key: 'mod+k mod+c',
    command: 'git.commit',
    description: 'Git commit',
    category: 'Git',
  },
  {
    id: 'gitPush',
    key: 'mod+k mod+p',
    command: 'git.push',
    description: 'Git push',
    category: 'Git',
  },
  {
    id: 'gitPull',
    key: 'mod+k mod+l',
    command: 'git.pull',
    description: 'Git pull',
    category: 'Git',
  },

  // ==================== Debug ====================
  {
    id: 'startDebugging',
    key: 'f5',
    command: 'debug.start',
    description: 'Start debugging',
    category: 'Debug',
  },
  {
    id: 'stopDebugging',
    key: 'shift+f5',
    command: 'debug.stop',
    description: 'Stop debugging',
    category: 'Debug',
  },
  {
    id: 'restartDebugging',
    key: 'mod+shift+f5',
    command: 'debug.restart',
    description: 'Restart debugging',
    category: 'Debug',
  },
  {
    id: 'stepOver',
    key: 'f10',
    command: 'debug.stepOver',
    description: 'Step over',
    category: 'Debug',
  },
  {
    id: 'stepInto',
    key: 'f11',
    command: 'debug.stepInto',
    description: 'Step into',
    category: 'Debug',
  },
  {
    id: 'stepOut',
    key: 'shift+f11',
    command: 'debug.stepOut',
    description: 'Step out',
    category: 'Debug',
  },
  {
    id: 'toggleBreakpoint',
    key: 'f9',
    command: 'debug.toggleBreakpoint',
    when: 'editorFocus',
    description: 'Toggle breakpoint',
    category: 'Debug',
  },

  // ==================== Terminal ====================
  {
    id: 'newTerminal',
    key: 'mod+shift+backtick',
    command: 'terminal.new',
    description: 'New terminal',
    category: 'Terminal',
  },
  {
    id: 'clearTerminal',
    key: 'mod+k',
    command: 'terminal.clear',
    when: 'terminalFocus',
    description: 'Clear terminal',
    category: 'Terminal',
  },

  // ==================== Settings ====================
  {
    id: 'openSettings',
    key: 'mod+,',
    command: 'settings.open',
    description: 'Open settings',
    category: 'Settings',
  },
  {
    id: 'openKeyboardShortcuts',
    key: 'mod+k mod+s',
    command: 'settings.openKeyboardShortcuts',
    description: 'Open keyboard shortcuts',
    category: 'Settings',
  },
];

// Group bindings by category for display
export function getKeybindingsByCategory(): Record<string, Keybinding[]> {
  const grouped: Record<string, Keybinding[]> = {};

  for (const binding of defaultKeybindings) {
    const category = binding.category || 'Other';
    if (!grouped[category]) {
      grouped[category] = [];
    }
    grouped[category].push(binding);
  }

  return grouped;
}
