"""Default hardware specifications seed data."""

DEFAULT_HARDWARE_SPECS = [
    # ==================== x86_64 CPU Tiers ====================
    # Tier names must match WorkspaceTier enum in shared/models/workspace.py
    {
        "tier": "starter",
        "display_name": "Starter",
        "description": "Basic development environment",
        "architecture": "x86_64",
        "vcpu": 2,
        "memory_mb": 4096,
        "gpu_type": None,
        "gpu_memory_gb": None,
        "gpu_count": 0,
        "is_gpu": False,
        "requires_gke": False,
        "storage_gb_default": 20,
        "storage_gb_max": 50,
        "hourly_rate_cents": 5,
        "is_available": True,
        "requires_subscription": None,
        "sort_order": 0,
    },
    {
        "tier": "pro",
        "display_name": "Pro",
        "description": "Standard development environment",
        "architecture": "x86_64",
        "vcpu": 4,
        "memory_mb": 8192,
        "gpu_type": None,
        "gpu_memory_gb": None,
        "gpu_count": 0,
        "is_gpu": False,
        "requires_gke": False,
        "storage_gb_default": 50,
        "storage_gb_max": 100,
        "hourly_rate_cents": 15,
        "is_available": True,
        "requires_subscription": "pro",
        "sort_order": 1,
    },
    {
        "tier": "power",
        "display_name": "Power",
        "description": "High-performance development environment",
        "architecture": "x86_64",
        "vcpu": 8,
        "memory_mb": 16384,
        "gpu_type": None,
        "gpu_memory_gb": None,
        "gpu_count": 0,
        "is_gpu": False,
        "requires_gke": False,
        "storage_gb_default": 100,
        "storage_gb_max": 200,
        "hourly_rate_cents": 35,
        "is_available": True,
        "requires_subscription": "team",
        "sort_order": 2,
    },
    {
        "tier": "enterprise",
        "display_name": "Enterprise",
        "description": "Maximum resources for enterprise workloads",
        "architecture": "x86_64",
        "vcpu": 16,
        "memory_mb": 32768,
        "gpu_type": None,
        "gpu_memory_gb": None,
        "gpu_count": 0,
        "is_gpu": False,
        "requires_gke": False,
        "storage_gb_default": 200,
        "storage_gb_max": 500,
        "hourly_rate_cents": 60,
        "is_available": True,
        "requires_subscription": "team",
        "sort_order": 3,
    },
    # ==================== GPU Tiers (x86 only) ====================
    {
        "tier": "gpu_starter",
        "display_name": "GPU Starter",
        "description": "NVIDIA T4 - inference and light training",
        "architecture": "x86_64",
        "vcpu": 4,
        "memory_mb": 16384,
        "gpu_type": "NVIDIA T4",
        "gpu_memory_gb": 16,
        "gpu_count": 1,
        "is_gpu": True,
        "requires_gke": True,
        "storage_gb_default": 100,
        "storage_gb_max": 200,
        "hourly_rate_cents": 80,
        "is_available": True,
        "requires_subscription": "pro",
        "sort_order": 20,
    },
    {
        "tier": "gpu_pro",
        "display_name": "GPU Pro",
        "description": "NVIDIA L4 - efficient AI/ML workloads",
        "architecture": "x86_64",
        "vcpu": 8,
        "memory_mb": 32768,
        "gpu_type": "NVIDIA L4",
        "gpu_memory_gb": 24,
        "gpu_count": 1,
        "is_gpu": True,
        "requires_gke": True,
        "storage_gb_default": 150,
        "storage_gb_max": 300,
        "hourly_rate_cents": 120,
        "is_available": True,
        "requires_subscription": "team",
        "sort_order": 21,
    },
    {
        "tier": "gpu_power",
        "display_name": "GPU Power",
        "description": "NVIDIA A100 - serious ML training and large models",
        "architecture": "x86_64",
        "vcpu": 16,
        "memory_mb": 65536,
        "gpu_type": "NVIDIA A100",
        "gpu_memory_gb": 40,
        "gpu_count": 1,
        "is_gpu": True,
        "requires_gke": True,
        "storage_gb_default": 500,
        "storage_gb_max": 1000,
        "hourly_rate_cents": 350,
        "is_available": True,
        "requires_subscription": "enterprise",
        "sort_order": 22,
    },
    # ==================== ML Accelerator Tiers ====================
    {
        "tier": "ml_inference",
        "display_name": "ML Inference",
        "description": "TPU v4 - cost-effective ML inference",
        "architecture": "x86_64",
        "vcpu": 4,
        "memory_mb": 32768,
        "gpu_type": "TPU v4",
        "gpu_memory_gb": 32,
        "gpu_count": 1,
        "is_gpu": True,
        "requires_gke": True,
        "storage_gb_default": 100,
        "storage_gb_max": 500,
        "hourly_rate_cents": 100,
        "is_available": True,
        "requires_subscription": "pro",
        "sort_order": 30,
    },
    {
        "tier": "ml_training",
        "display_name": "ML Training",
        "description": "TPU v5 - optimized for ML training workloads",
        "architecture": "x86_64",
        "vcpu": 8,
        "memory_mb": 65536,
        "gpu_type": "TPU v5",
        "gpu_memory_gb": 64,
        "gpu_count": 1,
        "is_gpu": True,
        "requires_gke": True,
        "storage_gb_default": 500,
        "storage_gb_max": 2000,
        "hourly_rate_cents": 200,
        "is_available": True,
        "requires_subscription": "team",
        "sort_order": 31,
    },
]
