"""Default subscription plans seed data."""

DEFAULT_PLANS = [
    {
        "name": "Free",
        "slug": "free",
        "description": "Get started with Podex for free",
        "price_monthly_cents": 0,
        "price_yearly_cents": 0,
        "currency": "USD",
        "tokens_included": 100000,
        "compute_credits_cents_included": 500,
        "storage_gb_included": 5,
        "max_agents": 1,
        "max_sessions": 3,
        "max_team_members": 1,
        "overage_allowed": False,
        "llm_margin_percent": 0,
        "compute_margin_percent": 20,
        "features": {
            "private_projects": False,
            "git_integration": True,
            "agent_memory": False,
            "planning_mode": False,
            "vision_analysis": False,
            "team_collaboration": False,
            "gpu_access": False,
            "community_support": True,
        },
        "is_active": True,
        "is_popular": False,
        "is_enterprise": False,
        "sort_order": 0,
    },
    {
        "name": "Pro",
        "slug": "pro",
        "description": "For professional developers and small teams",
        "price_monthly_cents": 2900,
        "price_yearly_cents": 29000,
        "currency": "USD",
        "tokens_included": 1000000,
        "compute_credits_cents_included": 2000,
        "storage_gb_included": 50,
        "max_agents": 5,
        "max_sessions": 10,
        "max_team_members": 5,
        "overage_allowed": True,
        "llm_margin_percent": 20,
        "compute_margin_percent": 20,
        "features": {
            "private_projects": True,
            "git_integration": True,
            "agent_memory": True,
            "planning_mode": True,
            "vision_analysis": True,
            "team_collaboration": True,
            "gpu_access": False,
            "advanced_analytics": True,
            "custom_agents": True,
            "email_support": True,
        },
        "is_active": True,
        "is_popular": True,
        "is_enterprise": False,
        "sort_order": 1,
    },
    {
        "name": "Max",
        "slug": "max",
        "description": "For growing teams with advanced needs",
        "price_monthly_cents": 9900,
        "price_yearly_cents": 99000,
        "currency": "USD",
        "tokens_included": 5000000,
        "compute_credits_cents_included": 5000,
        "storage_gb_included": 200,
        "max_agents": 20,
        "max_sessions": 50,
        "max_team_members": 20,
        "overage_allowed": True,
        "llm_margin_percent": 25,
        "compute_margin_percent": 20,
        "features": {
            "private_projects": True,
            "git_integration": True,
            "agent_memory": True,
            "planning_mode": True,
            "vision_analysis": True,
            "team_collaboration": True,
            "gpu_access": True,
            "advanced_analytics": True,
            "audit_logs": True,
            "custom_agents": True,
            "priority_support": False,
        },
        "is_active": True,
        "is_popular": False,
        "is_enterprise": False,
        "sort_order": 2,
    },
    {
        "name": "Enterprise",
        "slug": "enterprise",
        "description": "Custom solutions for large organizations",
        "price_monthly_cents": 0,
        "price_yearly_cents": 0,
        "currency": "USD",
        "tokens_included": 100000000,
        "compute_credits_cents_included": 100000,
        "storage_gb_included": 1000,
        "max_agents": 100,
        "max_sessions": 200,
        "max_team_members": 100,
        "overage_allowed": True,
        "llm_margin_percent": 30,
        "compute_margin_percent": 20,
        "features": {
            "private_projects": True,
            "git_integration": True,
            "agent_memory": True,
            "planning_mode": True,
            "vision_analysis": True,
            "team_collaboration": True,
            "gpu_access": True,
            "advanced_analytics": True,
            "audit_logs": True,
            "custom_agents": True,
            "priority_support": True,
            "sso_saml": True,
            "self_hosted_option": True,
            "sla": True,
            "dedicated_support": True,
        },
        "is_active": True,
        "is_popular": False,
        "is_enterprise": True,
        "sort_order": 3,
    },
]
