"""Default skill templates seed data."""

DEFAULT_SKILL_TEMPLATES = [
    # 1. CI/CD Deployment Template
    {
        "name": "CI/CD Deployment",
        "slug": "cicd_deployment",
        "description": "Template for creating deployment automation skills",
        "category": "deployment",
        "icon": "rocket",
        "default_triggers": ["deploy", "release", "ship"],
        "default_tags": ["deployment", "devops", "automation"],
        "required_tools": ["run_command", "read_file"],
        "step_templates": [
            {
                "name": "run_tests",
                "description": "Run test suite before deployment",
                "tool": "run_command",
                "parameters": {"command": "{{test_command}}"},
            },
            {
                "name": "build",
                "description": "Build the application",
                "tool": "run_command",
                "parameters": {"command": "{{build_command}}"},
            },
            {
                "name": "deploy",
                "description": "Deploy to {{environment}}",
                "tool": "run_command",
                "parameters": {"command": "{{deploy_command}}"},
            },
            {
                "name": "health_check",
                "description": "Verify deployment health",
                "tool": "run_command",
                "parameters": {"command": "{{health_check_command}}"},
            },
        ],
        "variables": [
            {
                "name": "test_command",
                "type": "string",
                "description": "Command to run tests",
                "default": "npm test",
            },
            {
                "name": "build_command",
                "type": "string",
                "description": "Command to build app",
                "default": "npm run build",
            },
            {
                "name": "deploy_command",
                "type": "string",
                "description": "Command to deploy",
                "default": "",
            },
            {
                "name": "health_check_command",
                "type": "string",
                "description": "Health check command",
                "default": "curl -f http://localhost/health",
            },
            {
                "name": "environment",
                "type": "enum",
                "description": "Target environment",
                "options": ["staging", "production"],
                "default": "staging",
            },
        ],
        "default_system_prompt": "You are deploying an application. Verify tests pass first.",
        "is_system": True,
        "is_active": True,
    },
    # 2. Test Runner Template
    {
        "name": "Test Runner",
        "slug": "test_runner",
        "description": "Template for creating test execution skills",
        "category": "testing",
        "icon": "check-circle",
        "default_triggers": ["test", "run tests", "verify"],
        "default_tags": ["testing", "qa", "verification"],
        "required_tools": ["run_command", "read_file"],
        "step_templates": [
            {
                "name": "run_unit_tests",
                "description": "Run unit tests",
                "tool": "run_command",
                "parameters": {"command": "{{unit_test_command}}"},
            },
            {
                "name": "run_integration_tests",
                "description": "Run integration tests",
                "tool": "run_command",
                "parameters": {"command": "{{integration_test_command}}"},
                "required": False,
            },
            {
                "name": "generate_coverage",
                "description": "Generate coverage report",
                "tool": "run_command",
                "parameters": {"command": "{{coverage_command}}"},
                "required": False,
            },
        ],
        "variables": [
            {
                "name": "unit_test_command",
                "type": "string",
                "description": "Unit test command",
                "default": "npm test",
            },
            {
                "name": "integration_test_command",
                "type": "string",
                "description": "Integration test command",
                "default": "npm run test:integration",
            },
            {
                "name": "coverage_command",
                "type": "string",
                "description": "Coverage report command",
                "default": "npm run coverage",
            },
        ],
        "default_system_prompt": "You are running tests. Focus on failures and coverage.",
        "is_system": True,
        "is_active": True,
    },
    # 3. Code Generator Template
    {
        "name": "Code Generator",
        "slug": "code_generator",
        "description": "Template for creating code generation skills",
        "category": "generation",
        "icon": "code",
        "default_triggers": ["generate", "create", "scaffold"],
        "default_tags": ["generation", "coder", "automation"],
        "required_tools": ["write_file", "read_file", "list_directory"],
        "step_templates": [
            {
                "name": "check_existing",
                "description": "Check for existing files",
                "tool": "list_directory",
                "parameters": {"path": "{{target_directory}}"},
            },
            {
                "name": "generate_code",
                "description": "Generate the code file",
                "tool": "write_file",
                "parameters": {"file_path": "{{output_file}}", "content": "{{generated_content}}"},
            },
            {
                "name": "generate_tests",
                "description": "Generate test file",
                "tool": "write_file",
                "parameters": {"file_path": "{{test_file}}", "content": "{{test_content}}"},
                "required": False,
            },
        ],
        "variables": [
            {
                "name": "target_directory",
                "type": "string",
                "description": "Directory for generated files",
                "default": "./src",
            },
            {
                "name": "output_file",
                "type": "string",
                "description": "Output file path",
                "default": "",
            },
            {"name": "test_file", "type": "string", "description": "Test file path", "default": ""},
            {
                "name": "component_type",
                "type": "enum",
                "description": "Type of component",
                "options": ["component", "service", "hook", "util"],
                "default": "component",
            },
        ],
        "default_system_prompt": "You are generating code. Follow project conventions.",
        "is_system": True,
        "is_active": True,
    },
    # 4. Documentation Template
    {
        "name": "Documentation",
        "slug": "documentation",
        "description": "Template for creating documentation skills",
        "category": "documentation",
        "icon": "file-text",
        "default_triggers": ["document", "docs", "readme"],
        "default_tags": ["documentation", "writer"],
        "required_tools": ["read_file", "write_file", "search_code"],
        "step_templates": [
            {
                "name": "analyze_code",
                "description": "Analyze code structure",
                "tool": "search_code",
                "parameters": {"pattern": "{{code_pattern}}"},
            },
            {
                "name": "read_existing",
                "description": "Read existing documentation",
                "tool": "read_file",
                "parameters": {"file_path": "{{doc_file}}"},
                "required": False,
            },
            {
                "name": "write_docs",
                "description": "Write documentation",
                "tool": "write_file",
                "parameters": {"file_path": "{{output_file}}", "content": "{{documentation}}"},
            },
        ],
        "variables": [
            {
                "name": "code_pattern",
                "type": "string",
                "description": "Pattern to find code to document",
                "default": "export",
            },
            {
                "name": "doc_file",
                "type": "string",
                "description": "Existing doc file to update",
                "default": "README.md",
            },
            {
                "name": "output_file",
                "type": "string",
                "description": "Output documentation file",
                "default": "README.md",
            },
            {
                "name": "doc_format",
                "type": "enum",
                "description": "Documentation format",
                "options": ["markdown", "jsdoc", "sphinx"],
                "default": "markdown",
            },
        ],
        "default_system_prompt": "You are writing documentation. Be clear and concise.",
        "is_system": True,
        "is_active": True,
    },
    # 5. Database Migration Template
    {
        "name": "Database Migration",
        "slug": "database_migration",
        "description": "Template for creating database migration skills",
        "category": "database",
        "icon": "database",
        "default_triggers": ["migrate", "migration", "schema"],
        "default_tags": ["database", "migration", "schema"],
        "required_tools": ["run_command", "read_file"],
        "step_templates": [
            {
                "name": "check_status",
                "description": "Check migration status",
                "tool": "run_command",
                "parameters": {"command": "{{status_command}}"},
            },
            {
                "name": "create_backup",
                "description": "Create database backup",
                "tool": "run_command",
                "parameters": {"command": "{{backup_command}}"},
                "required": False,
            },
            {
                "name": "run_migration",
                "description": "Run pending migrations",
                "tool": "run_command",
                "parameters": {"command": "{{migrate_command}}"},
            },
            {
                "name": "verify",
                "description": "Verify migration success",
                "tool": "run_command",
                "parameters": {"command": "{{verify_command}}"},
            },
        ],
        "variables": [
            {
                "name": "status_command",
                "type": "string",
                "description": "Check status command",
                "default": "npx prisma migrate status",
            },
            {
                "name": "backup_command",
                "type": "string",
                "description": "Backup command",
                "default": "",
            },
            {
                "name": "migrate_command",
                "type": "string",
                "description": "Migration command",
                "default": "npx prisma migrate deploy",
            },
            {
                "name": "verify_command",
                "type": "string",
                "description": "Verification command",
                "default": "npx prisma db pull --print",
            },
            {
                "name": "orm",
                "type": "enum",
                "description": "ORM/Migration tool",
                "options": ["prisma", "alembic", "knex", "typeorm"],
                "default": "prisma",
            },
        ],
        "default_system_prompt": "You are running database migrations. Check status first.",
        "is_system": True,
        "is_active": True,
    },
    # 6. API Integration Template
    {
        "name": "API Integration",
        "slug": "api_integration",
        "description": "Template for creating API integration skills",
        "category": "integration",
        "icon": "link",
        "default_triggers": ["integrate", "api", "connect"],
        "default_tags": ["api", "integration", "http"],
        "required_tools": ["web_fetch", "write_file", "read_file"],
        "step_templates": [
            {
                "name": "fetch_docs",
                "description": "Fetch API documentation",
                "tool": "web_fetch",
                "parameters": {"url": "{{docs_url}}"},
                "required": False,
            },
            {
                "name": "create_types",
                "description": "Create type definitions",
                "tool": "write_file",
                "parameters": {"file_path": "{{types_file}}", "content": "{{type_definitions}}"},
            },
            {
                "name": "create_client",
                "description": "Create API client",
                "tool": "write_file",
                "parameters": {"file_path": "{{client_file}}", "content": "{{client_code}}"},
            },
        ],
        "variables": [
            {
                "name": "docs_url",
                "type": "string",
                "description": "API documentation URL",
                "default": "",
            },
            {
                "name": "types_file",
                "type": "string",
                "description": "Types file path",
                "default": "./src/types/api.ts",
            },
            {
                "name": "client_file",
                "type": "string",
                "description": "Client file path",
                "default": "./src/lib/api-client.ts",
            },
            {
                "name": "auth_type",
                "type": "enum",
                "description": "Authentication type",
                "options": ["none", "api_key", "bearer", "oauth"],
                "default": "bearer",
            },
        ],
        "default_system_prompt": "You are integrating an API. Create typed clients.",
        "is_system": True,
        "is_active": True,
    },
    # 7. Security Audit Template
    {
        "name": "Security Audit",
        "slug": "security_audit",
        "description": "Template for creating security audit skills",
        "category": "security",
        "icon": "shield",
        "default_triggers": ["audit", "security", "vulnerabilities"],
        "default_tags": ["security", "audit", "compliance"],
        "required_tools": ["run_command", "search_code"],
        "step_templates": [
            {
                "name": "audit_deps",
                "description": "Audit dependencies",
                "tool": "run_command",
                "parameters": {"command": "{{audit_command}}"},
            },
            {
                "name": "scan_secrets",
                "description": "Scan for secrets",
                "tool": "search_code",
                "parameters": {"pattern": "{{secrets_pattern}}"},
            },
            {
                "name": "check_configs",
                "description": "Check security configurations",
                "tool": "read_file",
                "parameters": {"file_path": "{{config_file}}"},
                "required": False,
            },
        ],
        "variables": [
            {
                "name": "audit_command",
                "type": "string",
                "description": "Dependency audit command",
                "default": "npm audit",
            },
            {
                "name": "secrets_pattern",
                "type": "string",
                "description": "Pattern to find secrets",
                "default": "password|secret|api_key|token",
            },
            {
                "name": "config_file",
                "type": "string",
                "description": "Security config file",
                "default": "",
            },
        ],
        "default_system_prompt": "You are performing a security audit. Report vulnerabilities.",
        "is_system": True,
        "is_active": True,
    },
    # 8. Monitoring Setup Template
    {
        "name": "Monitoring Setup",
        "slug": "monitoring_setup",
        "description": "Template for creating monitoring and alerting skills",
        "category": "monitoring",
        "icon": "activity",
        "default_triggers": ["monitor", "alerts", "observability"],
        "default_tags": ["monitoring", "devops", "observability"],
        "required_tools": ["write_file", "run_command"],
        "step_templates": [
            {
                "name": "create_config",
                "description": "Create monitoring configuration",
                "tool": "write_file",
                "parameters": {"file_path": "{{config_file}}", "content": "{{monitoring_config}}"},
            },
            {
                "name": "setup_alerts",
                "description": "Configure alerting rules",
                "tool": "write_file",
                "parameters": {"file_path": "{{alerts_file}}", "content": "{{alerts_config}}"},
            },
            {
                "name": "verify_setup",
                "description": "Verify monitoring setup",
                "tool": "run_command",
                "parameters": {"command": "{{verify_command}}"},
            },
        ],
        "variables": [
            {
                "name": "config_file",
                "type": "string",
                "description": "Monitoring config path",
                "default": "./monitoring/config.yml",
            },
            {
                "name": "alerts_file",
                "type": "string",
                "description": "Alerts config path",
                "default": "./monitoring/alerts.yml",
            },
            {
                "name": "verify_command",
                "type": "string",
                "description": "Verification command",
                "default": "",
            },
            {
                "name": "platform",
                "type": "enum",
                "description": "Monitoring platform",
                "options": ["prometheus", "datadog", "newrelic", "grafana"],
                "default": "prometheus",
            },
        ],
        "default_system_prompt": "You are setting up monitoring. Configure metrics and alerts.",
        "is_system": True,
        "is_active": True,
    },
]
