// Extension Types
export type {
  ExtensionManifest,
  ExtensionCategory,
  ActivationEvent,
  ExtensionPermission,
  ExtensionContributions,
  CommandContribution,
  KeybindingContribution,
  ThemeContribution,
  LanguageContribution,
  GrammarContribution,
  SnippetContribution,
  ConfigurationContribution,
  ConfigurationProperty,
  ViewContribution,
  ViewContainerContribution,
  MenuContribution,
  MenuItemContribution,
  ExtensionState,
  ExtensionInfo,
  ExtensionActivationError,
  ExtensionContext,
  Disposable,
  Memento,
  Event,
  CancellationToken,
  ExtensionMessageType,
  ExtensionMessage,
  ApiCallMessage,
  ApiResponseMessage,
  EventMessage,
} from './types';

// Extension API
export type {
  PodexApi,
  WindowApi,
  WorkspaceApi,
  LanguagesApi,
  CommandsApi,
  EnvApi,
  QuickPickItem,
  QuickPickOptions,
  InputBoxOptions,
  ProgressOptions,
  ProgressLocation,
  Progress,
  ProgressMessage,
  StatusBarAlignment,
  StatusBarItem,
  OutputChannel,
  Terminal,
  TextEditor,
  TextEditorOptions,
  TextEditorEdit,
  TextEditorDecorationType,
  TextDocument,
  TextLine,
  TextDocumentChangeEvent,
  WorkspaceFolder,
  FileSystem,
  FileStat,
  FileType,
  FileSystemWatcher,
  WorkspaceConfiguration,
  WorkspaceEdit,
  TextEdit,
  DiagnosticCollection,
  Diagnostic,
  DiagnosticSeverity,
  DiagnosticTag,
  DiagnosticRelatedInformation,
  CompletionItemProvider,
  CompletionContext,
  CompletionTriggerKind,
  CompletionItem,
  CompletionItemKind,
  CompletionList,
  HoverProvider,
  Hover,
  DefinitionProvider,
  Definition,
  DefinitionLink,
  DocumentSymbolProvider,
  DocumentSymbol,
  SymbolInformation,
  SymbolKind,
  CodeActionProvider,
  CodeActionContext,
  CodeActionTriggerKind,
  CodeActionProviderMetadata,
  CodeAction,
  CodeLensProvider,
  CodeLens,
  DocumentFormattingEditProvider,
  OnTypeFormattingEditProvider,
  FormattingOptions,
  Command,
  DocumentSelector,
  DocumentFilter,
  Location,
  ProviderResult,
} from './ExtensionApi';

export { Uri, Position, Range, Selection, MarkdownString, CodeActionKind } from './ExtensionApi';

// Extension Host
export { useExtensionHostStore, useExtensionHost } from './ExtensionHost';
